#!/usr/bin/env node
// Why not: 型を手書きしない | Reason: schemas/ が唯一の契約正典であり、手書き型は ADR-0001 拘束1 が禁じるドリフト源になる
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile } from "json-schema-to-typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const checkMode = process.argv.includes("--check");

const targets = [
  ["philosophy-pack", "philosophy-pack"],
  ["design-intent", "design-intent"],
  ["evaluation", "evaluation"],
  ["run-manifest", "run-manifest"],
  ["ui-snapshot", "ui-snapshot"],
];

const banner = `/* generated by scripts/generate-types.mjs — DO NOT EDIT.
 * Source of truth: packages/spec/schemas/. Regenerate: pnpm --filter @tenetr/spec codegen */
`;

const outDir = join(root, "src", "generated");
mkdirSync(outDir, { recursive: true });

const stale = [];
for (const [schemaName, outName] of targets) {
  const ts = await compileFromFile(
    join(root, "schemas", `${schemaName}.schema.json`),
    {
      bannerComment: banner,
      additionalProperties: false,
      style: { singleQuote: false },
    },
  );
  const outPath = join(outDir, `${outName}.ts`);
  if (checkMode) {
    const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
    if (current !== ts) stale.push(outName);
  } else {
    writeFileSync(outPath, ts);
    console.log(`generated src/generated/${outName}.ts`);
  }
}

const indexContent = `${banner}export type { PhilosophyPack } from "./philosophy-pack.js";
export type { DesignIntentContract } from "./design-intent.js";
export type { EvaluationResult } from "./evaluation.js";
export type { RunManifest } from "./run-manifest.js";
export type { UISnapshot } from "./ui-snapshot.js";
`;
const indexPath = join(outDir, "index.ts");
if (checkMode) {
  const current = existsSync(indexPath) ? readFileSync(indexPath, "utf8") : "";
  if (current !== indexContent) stale.push("index");
  if (stale.length) {
    console.error(
      `stale generated types: ${stale.join(", ")} — run: pnpm --filter @tenetr/spec codegen`,
    );
    process.exit(1);
  }
  console.log("generated types are fresh");
} else {
  writeFileSync(indexPath, indexContent);
  console.log("generated src/generated/index.ts");
}
